/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface HealthLog {
    userId: string;
    date: Time;
    mood: string;
    concerns: string;
    symptoms: Array<string>;
    nutritionNotes: string;
}
export type Time = bigint;
export interface SOSAlert {
    id: bigint;
    status: Variant_resolved_active;
    userId: string;
    note: string;
    timestamp: Time;
}
export interface Notification {
    id: bigint;
    alertType: Variant_riskStatusChange_missedCheckIn_sosEvent;
    userId: string;
    isRead: boolean;
    message: string;
    timestamp: Time;
}
export interface NutritionTip {
    audioLabel: string;
    text: string;
}
export interface UserProfile {
    id: string;
    name: string;
    role: UserRole;
    zone?: string;
    dueDate?: Time;
    riskStatus: RiskStatus;
    language: Language;
    beneficiaries: Array<string>;
    village: string;
    weeksPregnant?: bigint;
    phone: string;
    assignedAshaId?: string;
    lastCheckIn?: Time;
}
export enum Language {
    hindi = "hindi",
    marathi = "marathi",
    gujarati = "gujarati"
}
export enum RiskStatus {
    red = "red",
    green = "green",
    yellow = "yellow"
}
export enum UserRole {
    admin = "admin",
    ashaWorker = "ashaWorker",
    pregnantWoman = "pregnantWoman"
}
export enum UserRole__1 {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_resolved_active {
    resolved = "resolved",
    active = "active"
}
export enum Variant_riskStatusChange_missedCheckIn_sosEvent {
    riskStatusChange = "riskStatusChange",
    missedCheckIn = "missedCheckIn",
    sosEvent = "sosEvent"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addNutritionTip(tip: NutritionTip): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole__1): Promise<void>;
    createNotification(userId: string, message: string, alertType: Variant_riskStatusChange_missedCheckIn_sosEvent): Promise<void>;
    createUserProfile(profile: UserProfile): Promise<void>;
    getActiveSOSAlertsByAsha(ashaId: string): Promise<Array<SOSAlert>>;
    getAshaBeneficiaryList(ashaId: string): Promise<Array<UserProfile>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole__1>;
    getHealthLogsForUser(userId: string): Promise<Array<HealthLog>>;
    getNotificationsForUser(userId: string): Promise<Array<Notification>>;
    getNutritionTips(): Promise<Array<NutritionTip>>;
    getRiskStatus(userId: string): Promise<RiskStatus>;
    getUserProfile(userId: string): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    markNotificationAsRead(notificationId: bigint): Promise<void>;
    resolveSOSAlert(alertId: bigint): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitHealthLog(log: HealthLog): Promise<void>;
    triggerSOSAlert(userId: string, note: string): Promise<void>;
    updateRiskStatus(userId: string, newStatus: RiskStatus): Promise<void>;
    updateUserProfile(id: string, updatedProfile: UserProfile): Promise<void>;
}
import type { Language as _Language, Notification as _Notification, RiskStatus as _RiskStatus, SOSAlert as _SOSAlert, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, UserRole__1 as _UserRole__1 } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addNutritionTip(arg0: NutritionTip): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addNutritionTip(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addNutritionTip(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole__1): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createNotification(arg0: string, arg1: string, arg2: Variant_riskStatusChange_missedCheckIn_sosEvent): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createNotification(arg0, arg1, to_candid_variant_n3(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createNotification(arg0, arg1, to_candid_variant_n3(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async createUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createUserProfile(to_candid_UserProfile_n4(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createUserProfile(to_candid_UserProfile_n4(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getActiveSOSAlertsByAsha(arg0: string): Promise<Array<SOSAlert>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveSOSAlertsByAsha(arg0);
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveSOSAlertsByAsha(arg0);
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAshaBeneficiaryList(arg0: string): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAshaBeneficiaryList(arg0);
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAshaBeneficiaryList(arg0);
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole__1> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole__1_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole__1_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHealthLogsForUser(arg0: string): Promise<Array<HealthLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHealthLogsForUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHealthLogsForUser(arg0);
            return result;
        }
    }
    async getNotificationsForUser(arg0: string): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotificationsForUser(arg0);
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotificationsForUser(arg0);
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNutritionTips(): Promise<Array<NutritionTip>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNutritionTips();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNutritionTips();
            return result;
        }
    }
    async getRiskStatus(arg0: string): Promise<RiskStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getRiskStatus(arg0);
                return from_candid_RiskStatus_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRiskStatus(arg0);
            return from_candid_RiskStatus_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: string): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markNotificationAsRead(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationAsRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationAsRead(arg0);
            return result;
        }
    }
    async resolveSOSAlert(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resolveSOSAlert(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resolveSOSAlert(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n4(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n4(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async submitHealthLog(arg0: HealthLog): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitHealthLog(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitHealthLog(arg0);
            return result;
        }
    }
    async triggerSOSAlert(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.triggerSOSAlert(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.triggerSOSAlert(arg0, arg1);
            return result;
        }
    }
    async updateRiskStatus(arg0: string, arg1: RiskStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRiskStatus(arg0, to_candid_RiskStatus_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRiskStatus(arg0, to_candid_RiskStatus_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateUserProfile(arg0: string, arg1: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserProfile(arg0, to_candid_UserProfile_n4(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserProfile(arg0, to_candid_UserProfile_n4(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_Language_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Language): Language {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_Notification_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Notification): Notification {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_RiskStatus_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RiskStatus): RiskStatus {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_SOSAlert_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SOSAlert): SOSAlert {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole__1_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole__1): UserRole__1 {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: {
        resolved: null;
    } | {
        active: null;
    };
    userId: string;
    note: string;
    timestamp: _Time;
}): {
    id: bigint;
    status: Variant_resolved_active;
    userId: string;
    note: string;
    timestamp: Time;
} {
    return {
        id: value.id,
        status: from_candid_variant_n15(_uploadFile, _downloadFile, value.status),
        userId: value.userId,
        note: value.note,
        timestamp: value.timestamp
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    name: string;
    role: _UserRole;
    zone: [] | [string];
    dueDate: [] | [_Time];
    riskStatus: _RiskStatus;
    language: _Language;
    beneficiaries: Array<string>;
    village: string;
    weeksPregnant: [] | [bigint];
    phone: string;
    assignedAshaId: [] | [string];
    lastCheckIn: [] | [_Time];
}): {
    id: string;
    name: string;
    role: UserRole;
    zone?: string;
    dueDate?: Time;
    riskStatus: RiskStatus;
    language: Language;
    beneficiaries: Array<string>;
    village: string;
    weeksPregnant?: bigint;
    phone: string;
    assignedAshaId?: string;
    lastCheckIn?: Time;
} {
    return {
        id: value.id,
        name: value.name,
        role: from_candid_UserRole_n19(_uploadFile, _downloadFile, value.role),
        zone: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.zone)),
        dueDate: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.dueDate)),
        riskStatus: from_candid_RiskStatus_n23(_uploadFile, _downloadFile, value.riskStatus),
        language: from_candid_Language_n25(_uploadFile, _downloadFile, value.language),
        beneficiaries: value.beneficiaries,
        village: value.village,
        weeksPregnant: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.weeksPregnant)),
        phone: value.phone,
        assignedAshaId: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.assignedAshaId)),
        lastCheckIn: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.lastCheckIn))
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    alertType: {
        riskStatusChange: null;
    } | {
        missedCheckIn: null;
    } | {
        sosEvent: null;
    };
    userId: string;
    isRead: boolean;
    message: string;
    timestamp: _Time;
}): {
    id: bigint;
    alertType: Variant_riskStatusChange_missedCheckIn_sosEvent;
    userId: string;
    isRead: boolean;
    message: string;
    timestamp: Time;
} {
    return {
        id: value.id,
        alertType: from_candid_variant_n34(_uploadFile, _downloadFile, value.alertType),
        userId: value.userId,
        isRead: value.isRead,
        message: value.message,
        timestamp: value.timestamp
    };
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    resolved: null;
} | {
    active: null;
}): Variant_resolved_active {
    return "resolved" in value ? Variant_resolved_active.resolved : "active" in value ? Variant_resolved_active.active : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    ashaWorker: null;
} | {
    pregnantWoman: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "ashaWorker" in value ? UserRole.ashaWorker : "pregnantWoman" in value ? UserRole.pregnantWoman : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    red: null;
} | {
    green: null;
} | {
    yellow: null;
}): RiskStatus {
    return "red" in value ? RiskStatus.red : "green" in value ? RiskStatus.green : "yellow" in value ? RiskStatus.yellow : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hindi: null;
} | {
    marathi: null;
} | {
    gujarati: null;
}): Language {
    return "hindi" in value ? Language.hindi : "marathi" in value ? Language.marathi : "gujarati" in value ? Language.gujarati : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole__1 {
    return "admin" in value ? UserRole__1.admin : "user" in value ? UserRole__1.user : "guest" in value ? UserRole__1.guest : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    riskStatusChange: null;
} | {
    missedCheckIn: null;
} | {
    sosEvent: null;
}): Variant_riskStatusChange_missedCheckIn_sosEvent {
    return "riskStatusChange" in value ? Variant_riskStatusChange_missedCheckIn_sosEvent.riskStatusChange : "missedCheckIn" in value ? Variant_riskStatusChange_missedCheckIn_sosEvent.missedCheckIn : "sosEvent" in value ? Variant_riskStatusChange_missedCheckIn_sosEvent.sosEvent : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SOSAlert>): Array<SOSAlert> {
    return value.map((x)=>from_candid_SOSAlert_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfile>): Array<UserProfile> {
    return value.map((x)=>from_candid_UserProfile_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Notification>): Array<Notification> {
    return value.map((x)=>from_candid_Notification_n32(_uploadFile, _downloadFile, x));
}
function to_candid_Language_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Language): _Language {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_RiskStatus_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RiskStatus): _RiskStatus {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n5(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole__1_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): _UserRole__1 {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    name: string;
    role: UserRole;
    zone?: string;
    dueDate?: Time;
    riskStatus: RiskStatus;
    language: Language;
    beneficiaries: Array<string>;
    village: string;
    weeksPregnant?: bigint;
    phone: string;
    assignedAshaId?: string;
    lastCheckIn?: Time;
}): {
    id: string;
    name: string;
    role: _UserRole;
    zone: [] | [string];
    dueDate: [] | [_Time];
    riskStatus: _RiskStatus;
    language: _Language;
    beneficiaries: Array<string>;
    village: string;
    weeksPregnant: [] | [bigint];
    phone: string;
    assignedAshaId: [] | [string];
    lastCheckIn: [] | [_Time];
} {
    return {
        id: value.id,
        name: value.name,
        role: to_candid_UserRole_n6(_uploadFile, _downloadFile, value.role),
        zone: value.zone ? candid_some(value.zone) : candid_none(),
        dueDate: value.dueDate ? candid_some(value.dueDate) : candid_none(),
        riskStatus: to_candid_RiskStatus_n8(_uploadFile, _downloadFile, value.riskStatus),
        language: to_candid_Language_n10(_uploadFile, _downloadFile, value.language),
        beneficiaries: value.beneficiaries,
        village: value.village,
        weeksPregnant: value.weeksPregnant ? candid_some(value.weeksPregnant) : candid_none(),
        phone: value.phone,
        assignedAshaId: value.assignedAshaId ? candid_some(value.assignedAshaId) : candid_none(),
        lastCheckIn: value.lastCheckIn ? candid_some(value.lastCheckIn) : candid_none()
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Language): {
    hindi: null;
} | {
    marathi: null;
} | {
    gujarati: null;
} {
    return value == Language.hindi ? {
        hindi: null
    } : value == Language.marathi ? {
        marathi: null
    } : value == Language.gujarati ? {
        gujarati: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole__1.admin ? {
        admin: null
    } : value == UserRole__1.user ? {
        user: null
    } : value == UserRole__1.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_riskStatusChange_missedCheckIn_sosEvent): {
    riskStatusChange: null;
} | {
    missedCheckIn: null;
} | {
    sosEvent: null;
} {
    return value == Variant_riskStatusChange_missedCheckIn_sosEvent.riskStatusChange ? {
        riskStatusChange: null
    } : value == Variant_riskStatusChange_missedCheckIn_sosEvent.missedCheckIn ? {
        missedCheckIn: null
    } : value == Variant_riskStatusChange_missedCheckIn_sosEvent.sosEvent ? {
        sosEvent: null
    } : value;
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    ashaWorker: null;
} | {
    pregnantWoman: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.ashaWorker ? {
        ashaWorker: null
    } : value == UserRole.pregnantWoman ? {
        pregnantWoman: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RiskStatus): {
    red: null;
} | {
    green: null;
} | {
    yellow: null;
} {
    return value == RiskStatus.red ? {
        red: null
    } : value == RiskStatus.green ? {
        green: null
    } : value == RiskStatus.yellow ? {
        yellow: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
